export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const SUBTRACT_INGREDIENT = "SUBTRACT_INGREDIENT";
export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE";
export const RESET_STATE = "RESET_STATE";
export const SET_BURGER_BUILDING_STATE = "SET_BURGER_BUILDING_STATE";
export const UPDATE_BURGER_BUILDING_STATE = "UPDATE_BURGER_BUILDING_STATE";

export const SET_INGREDIENTS_START = "SET_INGREDIENTS_START";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGREDIENTS_SUCCESS";
export const FETCH_INGREDIENTS_FAILURE = "FETCH_INGREDIENTS_FAILURE";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILURE = "PURCHASE_BURGER_FAILURE";
export const INIT_PURCHASE = "INIT_PURCHASE";

export const SET_ORDERS_START = "SET_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "FETCH_ORDERS_FAILURE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const AUTO_AUTH_SUCCESS = "AUTO_AUTH_SUCCESS";
export const AUTO_AUTH_FAILURE = "AUTO_AUTH_FAILURE";

export const LOGOUT = "LOGOUT";

export const CLEAR_MESAGES = "CLEAR_MESAGES";
