export const EMAIL_EXISTS = "EMAIL_EXISTS";
export const OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED";
export const TOO_MANY_ATTEMPTS_TRY_LATER = "TOO_MANY_ATTEMPTS_TRY_LATER";
export const EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND";
export const INVALID_PASSWORD = "INVALID_PASSWORD";
export const USER_DISABLED = "USER_DISABLED";
export const NETWORK_ERROR = "Network Error";
